services:
  database:
    image: 'postgres:16.1-alpine'
    ports:
      - '5432:5432'
    environment:
      - 'POSTGRES_USER=devicelab'
      - 'POSTGRES_DB=devicelab'
      - 'POSTGRES_PASSWORD=secret'